= CONTRIBUTING

:uri-oracle-oca: https://oca.opensource.oracle.com
:uri-lf-dco: https://developercertificate.org/

Oracle welcomes contributions to this repository from anyone.

If you want to submit a pull request to fix a bug or enhance an existing feature, please first open an issue and link to that issue when you submit your pull request.

If you have any questions about a possible submission, feel free to open an issue too.

== Contributing to the terraform-oci-oke repository

Pull requests are submitted under {uri-oracle-oca}[The Oracle Contributor Agreement] (OCA) and each commit must include the {uri-lf-dco}[Developer's Certificate of Origin] in the form of a `Signed-off-by` statement at the end of the commit message.

----
Signed-off-by: Your Name <you@example.org>
----

For pull requests to be accepted, you must use the same name and e-mail address as appears in the OCA signatories list.

The Developer's Certificate of Origin can be automatically added to your commit message by adding the `--signoff` or `-s` parameter:

----
  git commit --signoff
----

Only pull requests from contributors that can be verified as having
signed the OCA can be accepted.

=== Pull request process

. Fork this repository
. Create a branch in your fork to implement the changes. We recommend using
the issue number as part of your branch name, e.g. `1234-fixes`
. Ensure that any documentation is updated with the changes that are required
by your fix.
. Ensure that any samples are updated if the base image has been changed.
. Submit the pull request. *Do not leave the pull request blank*. Explain exactly
what your changes are meant to do and provide simple steps on how to validate
your changes. Ensure that you reference the issue you created as well.
We will assign the pull request to 2-3 people for review before it is merged.
